server_address: "localhost:8088"
admins: "../../source/admins.json"
authors: "../../source/authors.json"
books: "../../source/books.json"
genres: "../../source/genres.json"
instances: "../../source/instances.json"
languages: "../../source/languages.json"
productions: "../../source/productions.json"
readers: "../../source/readers.json"
users: "../../source/users.json"